# [START add_project]
swagger: "2.0"
info:
  description: "Guppy blockchain service."
  title: "Guppy Private Blockchain"
  version: "1.2.2"
host: "guppy-chain01.endpoints.[GPROJECT].cloud.goog"
# [END add_project]
x-google-endpoints:
- name: "guppy-chain01.endpoints.[GPROJECT].cloud.goog"
  target: "0.0.0.0"
  allowCors: "true"
#basePath: "/"
#x-google-allow: all
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "https"
- "http"

# This section requires all requests to any path to authenticate with Firebase.
security:
- guppy_node_service: []
- guppy_proxy_yodlee: []
- guppy_proxy_hibp: []
- firebase: []

paths:
  "/jsrpc":
    get:
      description: "JSON-RPC API"
      operationId: "jsonrpc-get"
      responses:
        200:
          description: OK
    post:
      description: "JSON-RPC API"
      operationId: "jsonrpc"
      responses:
        200:
          description: OK

  "/wsrpc":
    get:
      description: "WebSockets-RPC API"
      operationId: "wsrpc-get"
      responses:
        200:
          description: OK
    post:
      description: "WebSockets-RPC API"
      operationId: "wsrpc"
      responses:
        200:
          description: OK

  "/parity":
    get:
      description: "Parity UI"
      operationId: "parity-get"
      responses:
        200:
          description: OK
    post:
      description: "Parity UI"
      operationId: "parity"
      responses:
        200:
          description: OK

  "/dash":
    get:
      description: "Dashboard"
      operationId: "dashboard"
      responses:
        200:
          description: OK

# [START securityDef]
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  # This section configures authentication using Google OAuth2 ID Tokens.
  # ID Tokens can be obtained using OAuth2 clients, and can be used to access
  # your API on behalf of a particular user.
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    # Optional. Replace YOUR-CLIENT-ID with your client ID
    #x-google-audiences: ""
  # This section configures authentication using Google OAuth2 ID Tokens.
  # ID Tokens can be obtained using OAuth2 clients, and can be used to access
  # your API on behalf of a particular user.
  guppy_node_service:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "guppy-service-chain-client@guppy-service-chain.iam.gserviceaccount.com"
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/guppy-service-chain-client@guppy-service-chain.iam.gserviceaccount.com"
    # Optional. Replace YOUR-CLIENT-ID with your client ID
    #x-google-audiences: ""
  guppy_proxy_yodlee:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "guppy-proxy-yodlee-client@guppyproxyyodlee.iam.gserviceaccount.com"
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/guppy-proxy-yodlee-client@guppyproxyyodlee.iam.gserviceaccount.com"
  guppy_proxy_hibp:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "guppy-proxy-hibp-client@guppy-proxy-hibp.iam.gserviceaccount.com"
    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/guppy-proxy-hibp-client@guppy-proxy-hibp.iam.gserviceaccount.com"
  # This section configures authentication using Firebase Auth.
  # [START firebaseAuth]
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/guppy-service"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "guppy-service"
  # [END firebaseAuth]
# [END securityDef]
